### PR TITLE
Fix pagination for user listing

### LINKED ISSUE #122: Pagination info for users endpoint is missing
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
It is currently returning the following as a Link header in the response. The only value that changes is "per_page". 
`</users?page=1&per_page=1>; rel="last"`
`x-total-count` is also always 1.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Make a request to the `/users` endpoint. 

**- What is the expected behavior?**
I expect the Link response header to be like the orders pagination information:
`</users/all/orders?page=2&per_page=50>; rel="next", </users/all/orders?page=6&per_page=50>; rel="last"`
And I expect `x-total-count` to return the correct total count.

### PR DESCRIPTION
**Pull request by mraerino**
Fixes #122

**- Summary**

There was an issue with counting total records in queries with joins / groups. An update of Gorm fixed this.
Since the tests are actually not mocking gorm, I am confident that the upgrade will not break anything.

**- Test plan**

I added tests for verifying the pagination headers for *user* and *order* endpoints.

**- Description for the changelog**

Fix pagination on user listing endpoint

### CODE REVIEW

File: api/utils_test.go [hunk 1]
```diff
@@ -252,9 +254,6 @@ func loadTestData(t *testing.T, db *gorm.DB) *TestData {
 	require.NoError(t, db.Create(testData.firstLineItem).Error)
 	require.NoError(t, db.Create(testData.firstOrder).Error)
 	require.NoError(t, db.Create(testData.firstTransaction).Error)
-	for _, d := range testData.firstOrder.Downloads {
-		require.NoError(t, db.Create(d).Error)
-	}
```
Comment (mraerino) [inline api/utils_test.go]: Gorm will now create foreign objects by itself so this is obsolete
